package engineImpl

const FINANCIAL_RISK_TOLERANCE = "Financial Risk Tolerance"
const PSYCHOLOGICAL_RISK_TOLERANCE = "Psychological Risk Tolerance"
const TIME_FLEXIBILITY = "Time Flexibility"
const FINANCIAL_KNOWLEDGE = "Financial Knowledge"
const COGNITIVE_BIAS_RESISTANCE = "Cognitive Bias Resistance"

var CATEGORIES = []string{FINANCIAL_RISK_TOLERANCE, PSYCHOLOGICAL_RISK_TOLERANCE, TIME_FLEXIBILITY, FINANCIAL_KNOWLEDGE, COGNITIVE_BIAS_RESISTANCE}
